# Jekyll configuration for OpenAI Agents GitHub Pages
title: OpenAI Agents for Laravel
description: Progressive enhancement architecture for OpenAI agents in Laravel
url: https://sapiensly.github.io/openai-agents
baseurl: /openai-agents

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github

# Include
include:
  - _pages
  - assets

# SEO
author:
  name: Sapiensly
  email: ed@sapiensly.com
  bio: Progressive enhancement architecture for OpenAI agents
  location: Earth
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/sapiensly

# Social media
social:
  - name: GitHub
    url: https://github.com/sapiensly/openai-agents
  - name: Packagist
    url: https://packagist.org/packages/sapiensly/openai-agents

# Analytics (optional)
google_analytics: # UA-XXXXXXXXX-X

# Comments (optional)
disqus:
  shortname: # your-disqus-shortname 